apiVersion: v1
kind: Pod
metadata:
  name: nginx-emptydir
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: nginx-cache
        mountPath: /usr/share/nginx/html/cache
  volumes:
    - name: nginx-cache
      emptyDir: {}
